Header header

# deprecated (SDC-71668), do not use anymore
bool velocity_is_set
float64 velocity

# deprecated (SDC-71668), switch to kOdometrySteering
bool steering_is_set
float64 steering

# deprecated (SDC-71668), switch to kOdometryWheelVelocities
bool wheel_velocities_is_set
WheelVelocities wheel_velocities

# deprecated (SDC-71668), do not use anymore
bool shaft_velocity_is_set
float64 shaft_velocity