---
/sdc/online_fgo:
    ros__parameters:
      use_sim_time: true
      GNSSFGO:
        verbose: false
        useIMUAsTimeReference: false
        bufferSize: 10
        optFrequency: 10 #in Hz
        calcErrorOnOpt: true
        cleanIMUonInit: true    # set this flag to clean the imu data before the timestamp of the initializing state
        useHeaderTimestamp: true
        calibGravity: true
        #pubPoseVel: true
        #pubFGOState: true
        #pubPVTError: true
        #pubTimer: true
        #msg_lower_bound: 5000000 # 5 ms

        Initialization:
          initSigmaX: [ 2., 2., 2., 1., 1., 2. ] #first 3 for Rot in degree, other for translation in m
          initSigmaV: [ 1., 1., 1. ]
          initSigmaW: [ 0.05, 0.05, 0.05]
          initSigmaB: [ 0.5, 0.5, 0.5, 0.05, 0.05, 0.05] #first for b_a, second for b_g in degree
          initSigmaC: [ 1000., 10. ] #cb in m, cd in m/s

        IMUPreintegrator:
          # mine bkup
          accelerometerSigma: 0.000483 #3.9939570888238808e-04 #8e-4 # 8e-4
          integrationSigma: 1e-7 # 1e-4
          gyroscopeSigma: 0.0000872887264338 #1.5636343949698187e-05   #52e-4 # 52e-5
          biasAccSigma: 0.0049 # 4e-4 # 4e-4
          biasOmegaSigma: 0.00000145 # 87e-5
          biasAccOmegaInt: 0.00001 # 0.00001

          # kitti
          # accelerometerSigma: 0.008077134407821842 #3.9939570888238808e-04 #8e-4 # 8e-4
          # integrationSigma: 1e-4 # 1e-4
          # gyroscopeSigma: 0.0006939335887264338 #1.5636343949698187e-05   #52e-4 # 52e-5
          # biasAccSigma: 4e-4 # 4e-4
          # biasOmegaSigma: 87e-5 # 87e-5
          # biasAccOmegaInt: 0.00001 # 0.00001

        Graph:
          publishResiduals: false
          IMUMeasurementFrequency: 100
          useGPPriorFactor: true
          gpType: 'WNOJ'  # 'WNOA'
          useGPInterpolatedFactor: true
          useEstimatedVarianceAfterInit: false

          AutoDiffNormalFactor: true
          AutoDiffGPInterpolatedFactor: true
          AutoDiffGPMotionPriorFactor: true
          GPInterpolatedFactorCalcJacobian: true

          StateMeasSyncUpperBound: 0.03
          StateMeasSyncLowerBound: -0.03
          useMMFactor: false
          useConstDriftFactor: false

          noiseModelClockFactor: "huber"
          robustParamClockFactor: 10.
          constDriftStd: 0.5
          constBiasStd: .1
          motionModelStd: 1.
          angularRateStd: 0.05
          magnetometerStd: 0.01

          NoOptimizationWhileNoMeasurement: false
          NoOptimizationNearZeroVelocity: false
          VoteNearZeroVelocity: 0.2  # 20%
          NoOptimizationAfterStates: 0

        VehicleParameters:
          # IMURot: [1., 0., 0., 0., -1., 0., 0., 0., -1.]
          transIMUToReference: [0.0, 0.0, 0.0]
          rotIMUToReference: [1., 0., 0., 0., 1., 0., 0., 0., 1.]
          #transIMUToReference: [ 0., 0., -0.36 ]  #ca
          #rotIMUToReference: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
          transIMUToGNSSAnt1: [0.0, 0.0, 0.0]
          transIMUToGNSSAnt2: [0.0, 0.0, 0.0]

          transIMUToLiDAR: [0.0, 0., 0.0]
          transIMUToCorrevit: [0.0, 0.0, 0.0]
          #transIMUToCorrevit: [0., 0., 0.]
          rotIMUToLiDAR: [1., 0., 0., 0., 1., 0., 0., 0., 1. ]
          #transIMUToLiDAR: [ 0., 0., 0. ]  # ca
          #rotIMUToLiDAR: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        # Integrators: ["IRTPVALCIntegrator", "UbloxLCIntegrator", "CorrevitIntegrator"]   # ["UbloxIntegrator", "CorrevitIntegrator", "GNSSTCIntegrator", "LIOIntegrator"]
        # Integrators: ["IRTPVALCIntegrator", "SdcOdomIntegrator"]   # ["UbloxIntegrator", "CorrevitIntegrator", "GNSSTCIntegrator", "LIOIntegrator"]
        Integrators: ["IRTPVALCIntegrator"]
        # Integrators: ["GNSSTCIntegrator"]
        # Integrators: ["IRTPVALCIntegrator", "GNSSTCIntegrator"]
        # Integrators: ["GNSSTCIntegrator"]

        Optimizer:
          #undefined, BatchFixedLag, IncrementalFixedLag
          # smootherType: 'IncrementalFixedLag'
          smootherType: 'BatchFixedLag'
          smootherLag: 10. #marginalization threshhold
          #QcGPWNOJInterpolator: 1000.
          #QcGPWNOJMotionPrior: 10000.
          QcGPWNOJInterpolatorFull: [ 1000., 1000., 1000., 1000., 1000., 1000. ]
          QcGPWNOJMotionPriorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
          #QcGPWNOAInterpolator: 0.5
          #QcGPWNOAMotionPrior: 0.5
          QcGPWNOAInterpolatorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
          QcGPWNOAMotionPriorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
